# Site settings
title: My first blog
description: This is my first blog
theme: jekyll-theme-midnight

# Build settings
exclude: [vendor]

# Github settings - will be filled normally by github-pages
# repository: myGithubUser/myGithubRepositoryName
