# Site settings
title: My first blog
description: This is my first blog
theme: jekyll-theme-midnight

# Build settings
exclude: [vendor]

# Github settings - will be filled normally by github-pages
url: "https://ibiber.github.io"
baseurl: "/gh-pages.jeykll.docker.demo"
repository: iBiber/gh-pages.jeykll.docker.demo
